apiVersion: apps/v1
kind: Deployment
metadata:
  name: osmcha-adiff-service-worker
  labels:
    app: osmcha-adiff-service-worker
    environment: {{ .Values.config.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.adiff_service.replicas}}
  selector:
    matchLabels:
      app: osmcha-adiff-service-worker
  template:
    metadata:
      labels:
        app: osmcha-adiff-service-worker
    spec:
      containers:
        - name: osmcha-adiff-service-worker
          image: {{ .Values.adiff_service.image.repository }}:{{ .Values.adiff_service.image.tag }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - yarn update-queue
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: osmcha-real-changesets-credentials
                  key: access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: osmcha-real-changesets-credentials
                  key: secret_key
            - name: OsmchaAdminToken
              valueFrom:
                secretKeyRef:
                  name: osmcha-admin-token
                  key: osmcha_admin_token
            - name: RedisServer
              value: {{ .Values.adiff_service.redis_url }}
            - name: NumberOfWorkers
              value: {{ .Values.adiff_service.worker_count | quote }}
