apiVersion: apps/v1
kind: Deployment
metadata:
  name: osmcha-api
  labels:
    app: osmcha
    environment: {{ .Values.config.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: osmcha-api
  template:
    metadata:
      labels:
        app: osmcha-api
    spec:
      containers:
      - name: osmcha-api
        image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
        command: ["/gunicorn.sh"]
        env:
        - name: POSTGRES_HOST
          value: {{ .Values.api.postgres_host}}
        - name: PGHOST
          value: {{ .Values.api.postgres_host}}
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: {{ .Values.api.postgres_user}}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: osmcha-db-credentials
              key: password
        - name: POSTGRES_DATABASE
          value: {{ .Values.api.postgres_database}}
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret-key
              key: django_secret_key
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings.production"
        - name: OSMCHA_FRONTEND_VERSION
          value: {{ .Values.api.frontend_tag }}
        - name: OAUTH_OSM_KEY
          valueFrom:
            secretKeyRef:
              name: osm-app-credentials
              key: access_key
        - name: OAUTH_OSM_SECRET
          valueFrom:
            secretKeyRef:
              name: osm-app-credentials
              key: secret_key
        - name: OAUTH_REDIRECT_URI
          value: "https://{{ .Values.ui.host }}/oauth-landing.html"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 600 # 10 minutes, static file collection takes a while
          timeoutSeconds: 30
      {{- if .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.api.nodeSelector | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: osmcha-api
spec:
  selector:
    app: osmcha-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
