apiVersion: apps/v1
kind: Deployment
metadata:
  name: osmcha-app
  labels:
    app: osmcha
    environment: {{ .Values.config.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: osmcha-app
  template:
    metadata:
      labels:
        app: osmcha-app
    spec:
      initContainers:
      - name: osmcha-init
        image: {{ .Values.app.api.image.repository }}:{{ .Values.app.api.image.tag }}
        command: ["python", "manage.py", "collectstatic", "--noinput"]

        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings.production"
        volumeMounts:
        - name: staticfiles
          mountPath: /app/staticfiles
      containers:
      - name: osmcha-api
        image: {{ .Values.app.api.image.repository }}:{{ .Values.app.api.image.tag }}
        args: ["gunicorn", "config.wsgi", "-b", "0.0.0.0:5000", "--access-logfile", "-", "--timeout", "120", "--workers", "4", "--threads", "16"]
        resources:
          {{- toYaml .Values.app.api.resources | nindent 10 }}
        env:
        - name: PGHOST
          value: {{ .Values.app.api.postgres_host}}
        - name: PGPORT
          value: "5432"
        - name: PGUSER
          value: {{ .Values.app.api.postgres_user}}
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: osmcha-db-credentials
              key: password
        - name: PGDATABASE
          value: {{ .Values.app.api.postgres_database}}
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret-key
              key: django_secret_key
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings.production"
        - name: OAUTH2_OSM_KEY
          valueFrom:
            secretKeyRef:
              name: osm-app-credentials
              key: access_key
        - name: OAUTH2_OSM_SECRET
          valueFrom:
            secretKeyRef:
              name: osm-app-credentials
              key: secret_key
        - name: OAUTH_REDIRECT_URI
          value: "https://{{ .Values.app.host }}/authorized"
        - name: REDIS_URL
          value: {{ .Values.app.api.redis_url }}
        - name: DJANGO_SECURE_SSL_REDIRECT
          value: "False"
        - name: DJANGO_ENABLE_CHANGESET_COMMENTS
          value: "True"
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: staticfiles
          mountPath: /staticfiles
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 5000
            scheme: HTTP
          # initialDelaySeconds: 60
          timeoutSeconds: 60
      - name: frontend-nginx
        image: "{{ .Values.app.ui.image.repository }}:{{ .Values.app.ui.image.tag }}"
        env:
        - name: BACKEND_URL
          value: http://localhost:5000
        ports:
        - containerPort: 80
        volumeMounts:
          - name: staticfiles
            mountPath: /srv/www/static/django
            readOnly: true
      volumes:
      - name: staticfiles
        emptyDir: {}
      {{- if .Values.app.nodeSelector }}  
      nodeSelector:
        {{- toYaml .Values.app.nodeSelector | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: osmcha-app
spec:
  selector:
    app: osmcha-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
