apiVersion: batch/v1
kind: CronJob
metadata:
  name: osmcha-fetch-changesets-cronjob
  labels:
    app: osmcha
    environment: {{ .Values.config.environment }}
    release: {{ .Release.Name }}
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: osmcha-fetch-changesets
            image: {{ .Values.app.api.image.repository }}:{{ .Values.app.api.image.tag }}
            imagePullPolicy: IfNotPresent
            # Sometimes the fetchchangesets command hangs, so we set a timeout of 10 minutes
            # to prevent the job from hanging idly.
            # The timeout command kills the process after 10 minutes and forces the job to restart
            # with the next scheduled run.
            command:
            - /bin/sh
            - -c
            - timeout 3600s python manage.py fetchchangesets
            env:
            - name: PGHOST
              value: {{ .Values.app.api.postgres_host}}
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: {{ .Values.app.api.postgres_user}}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: osmcha-db-credentials
                  key: password
            - name: PGDATABASE
              value: {{ .Values.app.api.postgres_database}}
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret-key
                  key: django_secret_key
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings.production"
            - name: REDIS_URL
              value: {{ .Values.app.api.redis_url }}
          restartPolicy: Never
