apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osmcha-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: nginx
  {{- if .Values.config.enable_tls }}
  tls:
  - hosts:
    - "{{ .Values.app.host }}"
    secretName: osmcha-tls
  {{- end }}
  rules:
  - host: "{{ .Values.app.host }}"
    http:
      paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: osmcha-app
                port: 
                  number: 80