# Kubernetes Job to run the database migrations for OSMCha as Helm install/upgrade hook
apiVersion: batch/v1
kind: Job
metadata:
  name: osmcha-migrations-job
  labels:
    app: osmcha
    environment: {{ .Values.config.environment }}
    release: {{ .Release.Name }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: osmcha
        environment: {{ .Values.config.environment }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: osmcha-migrations
        image: {{ .Values.app.api.image.repository }}:{{ .Values.app.api.image.tag }}
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - python manage.py migrate
        env:
        - name: PGHOST
          value: {{ .Values.app.api.postgres_host}}
        - name: PGPORT
          value: "5432"
        - name: PGUSER
          value: {{ .Values.app.api.postgres_user}}
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: osmcha-db-credentials
              key: password
        - name: PGDATABASE
          value: {{ .Values.app.api.postgres_database}}
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret-key
              key: django_secret_key
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings.production"
        - name: REDIS_URL
          value: {{ .Values.app.api.redis_url }}
      restartPolicy: Never
  backoffLimit: 0
  parallelism: 1
  completions: 1
