apiVersion: v1
kind: Secret
metadata:
  name: osm-app-credentials
type: Opaque
data:
  access_key: {{ .Values.secrets.osm_access_key | b64enc | quote}}
  secret_key: {{ .Values.secrets.osm_secret_key | b64enc | quote}}

---

apiVersion: v1
kind: Secret
metadata:
  name: osmcha-db-credentials
type: Opaque
data:
  password: {{ .Values.secrets.osmcha_db_password | b64enc | quote}}

---

apiVersion: v1
kind: Secret
metadata:
  name: osmcha-real-changesets-credentials
type: Opaque
data:
  access_key: {{ .Values.secrets.real_changesets_access_key | b64enc | quote}}
  secret_key: {{ .Values.secrets.real_changesets_secret_key | b64enc | quote}}

---

apiVersion: v1
kind: Secret
metadata:
  name: osmcha-admin-token
type: Opaque
data:
  osmcha_admin_token: {{ .Values.secrets.osmcha_admin_token | b64enc | quote}}
