apiVersion: v1
kind: Secret
metadata:
  name: osm-app-credentials
type: Opaque
data:
  access_key: {{ .Values.secrets.osm_access_key | b64enc | quote}}
  secret_key: {{ .Values.secrets.osm_secret_key | b64enc | quote}}
