config:
  environment: production
  enable_tls: true

secrets:
  osm_access_key:
  osm_secret_key:

api:
  replicas: 1
  image:
    repository: ghcr.io/sunu/osmcha-django
    tag: test2
  postgres_host: osmcha-test.cz9ktd5n6tn5.us-east-1.rds.amazonaws.com
  postgres_user: postgres
  postgres_database: osmcha
  frontend_tag: v0.86.0-production # should we use this?


# OSMCha UI - templates/ui.yaml
ui:
  replicas: 1
  nodeSelector: {}
  image:
    repository: ghcr.io/sunu/osmcha-frontend
    tag: test9
  host: osmcha-test.ds.io

  # Nginx config - templates/config-map.yaml
  nginxConfig:
    mime.types: |
      types {
          text/html                                        html htm shtml;
          text/css                                         css;
          text/xml                                         xml;
          image/gif                                        gif;
          image/jpeg                                       jpeg jpg;
          application/javascript                           js;
          image/png                                        png;
          image/svg+xml                                    svg svgz;
          image/tiff                                       tif tiff;
          image/x-icon                                     ico;
          image/x-jng                                      jng;
          application/font-woff                            woff;
          application/json                                 json;
          application/zip                                  zip;
      }
    nginx.conf: |
      worker_processes 4;

      events {
        worker_connections 1024;
      }

      http {
        include mime.types;
        index index.html;
        sendfile on;

        server {
          listen 80 default_server;

          access_log off;
          add_header X-Clacks-Overhead          "GNU DCG; JK; MK";
          add_header Feature-Policy             "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'";

          location ~ ^/static.* {
            root /assets;
            expires 14d;
          }

          location / {
            root /assets;
            try_files $uri $uri/ /index.html;
            expires 1s;
          }
        }
      }
