config:
  environment: production
  enable_tls: true

secrets:
  osm_access_key:
  osm_secret_key:
  osmcha_db_password:
  real_changesets_access_key:
  real_changesets_secret_key:
  osmcha_admin_token:

app:
  replicas: 1
  host: osmcha.org

  api:
    image:
      repository: ghcr.io/osmcha/osmcha-django
      tag: v4.26.3
    resources:
      requests:
        memory: "4G"
        cpu: "2"
      limits:
        memory: "8G"
        cpu: "4"
    postgres_host: osmcha-database.cz9ktd5n6tn5.us-east-1.rds.amazonaws.com
    postgres_user: postgres
    postgres_database: osmcha
    redis_url: redis://redis-master:6379

  # OSMCha frontend - runs as a sidecar to the API
  ui:
    nodeSelector: {}
    image:
      repository: ghcr.io/osmcha/osmcha-frontend
      tag: v1.2.3
